import { ROUTES } from "./routes";

export const NAVBAR_ITEMS = [
  {
    NAME: ROUTES.HOME.NAME,
    PATH: ROUTES.HOME.PATH,
  },
  {
    NAME: ROUTES.EXPERIENCE.NAME,
    PATH: ROUTES.EXPERIENCE.PATH,
  },
  {
    NAME: ROUTES.SKILLS.NAME,
    PATH: ROUTES.SKILLS.PATH,
  },
  {
    NAME: ROUTES.PROJECTS.NAME,
    PATH: ROUTES.PROJECTS.PATH,
  },
  {
    NAME: ROUTES.CONTACT.NAME,
    PATH: ROUTES.CONTACT.PATH,
  },
];
